add app icon for macos
ztjhz/BetterChatGPT pull request #321
Opened 2023-06-02 09:38 UTC by mariodian

I propose this small change to the app's icon so it's more in line with Apple's design guidelines (added padding and shadow). 

![new macos icon](https://github.com/ztjhz/BetterChatGPT/assets/3636406/b7308130-459d-40a7-91af-16276f0d601e)

I left the original icon intact so the change doesn't affect Linux and Windows users.

I believe changes to window and tray in electron/index.cjs aren't necessary because:

1) there's no window icon in any MacOS (only OSX which is fairly old)
2) the app has no ability to be displayed in top menu bar currently (I assume that's what electron's Tray() is in MacOS)

If you want me to add the icon to window and tray though, I'm happy to do so.

2023-06-02 16:01 UTC, ztjhz requested changes
Nice work! Just need a new line at the end of the `package.json` file

2023-06-03 08:26 UTC, mariodian commented on package.json
> +}
I will as soon as I get back to the computer.

2023-06-03 08:37 UTC, mariodian commented on package.json
> +}
Since it's such a small PR I just fixed the existing commit instead of making another one. Hope it's ok.

2023-06-03 08:41 UTC, mariodian commented on package.json
> +}
I may have some issue with my editor. I can't see the new line in the fixed commit but I do see it in the file locally. Could you please check what it looks like on your end?

2023-06-06 13:03 UTC, ztjhz approved these changes

2023-06-06 13:04 UTC, merged